import os


# Queue settings
QUEUE_CONNECTION_HOST = os.getenv("ENV_QUEUE_CONNECTION_HOST")
QUEUE_MSG_QUEUE_NAME = os.getenv("ENV_QUEUE_MSG_QUEUE_NAME")

QUEUE_BLOCKED_CONNECTION_TIMEOUT = int(os.getenv("ENV_QUEUE_BLOCKED_CONNECTION_TIMEOUT") or "0")
